#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")/.."

SAMPLE_PATH="samples"
OUTPUT_PATH="output"

input_paths=(
    "$SAMPLE_PATH/easy/1EASY.bmp"
    "$SAMPLE_PATH/easy/2EASY.bmp"
    "$SAMPLE_PATH/easy/3EASY.bmp"
    "$SAMPLE_PATH/easy/4EASY.bmp"
    "$SAMPLE_PATH/easy/5EASY.bmp"
    "$SAMPLE_PATH/easy/6EASY.bmp"
    "$SAMPLE_PATH/easy/7EASY.bmp"
    "$SAMPLE_PATH/easy/8EASY.bmp"
    "$SAMPLE_PATH/easy/9EASY.bmp"
    "$SAMPLE_PATH/easy/10EASY.bmp"
    "$SAMPLE_PATH/medium/1MEDIUM.bmp"
    "$SAMPLE_PATH/medium/2MEDIUM.bmp"
    "$SAMPLE_PATH/medium/3MEDIUM.bmp"
    "$SAMPLE_PATH/medium/4MEDIUM.bmp"
    "$SAMPLE_PATH/medium/5MEDIUM.bmp"
    "$SAMPLE_PATH/medium/6MEDIUM.bmp"
    "$SAMPLE_PATH/medium/7MEDIUM.bmp"
    "$SAMPLE_PATH/medium/8MEDIUM.bmp"
    "$SAMPLE_PATH/medium/9MEDIUM.bmp"
    "$SAMPLE_PATH/medium/10MEDIUM.bmp"
    "$SAMPLE_PATH/hard/1HARD.bmp"
    "$SAMPLE_PATH/hard/2HARD.bmp"
    "$SAMPLE_PATH/hard/3HARD.bmp"
    "$SAMPLE_PATH/hard/4HARD.bmp"
    "$SAMPLE_PATH/hard/5HARD.bmp"
    "$SAMPLE_PATH/hard/6HARD.bmp"
    "$SAMPLE_PATH/hard/7HARD.bmp"
    "$SAMPLE_PATH/hard/8HARD.bmp"
    "$SAMPLE_PATH/hard/9HARD.bmp"
    "$SAMPLE_PATH/hard/10HARD.bmp"
    "$SAMPLE_PATH/impossible/1IMPOSSIBLE.bmp"
    "$SAMPLE_PATH/impossible/2IMPOSSIBLE.bmp"
    "$SAMPLE_PATH/impossible/3IMPOSSIBLE.bmp"
    "$SAMPLE_PATH/impossible/4IMPOSSIBLE.bmp"
    "$SAMPLE_PATH/impossible/5IMPOSSIBLE.bmp"
)

output_paths=(
    "$OUTPUT_PATH/output_1EASY.bmp"
    "$OUTPUT_PATH/output_2EASY.bmp"
    "$OUTPUT_PATH/output_3EASY.bmp"
    "$OUTPUT_PATH/output_4EASY.bmp"
    "$OUTPUT_PATH/output_5EASY.bmp"
    "$OUTPUT_PATH/output_6EASY.bmp"
    "$OUTPUT_PATH/output_7EASY.bmp"
    "$OUTPUT_PATH/output_8EASY.bmp"
    "$OUTPUT_PATH/output_9EASY.bmp"
    "$OUTPUT_PATH/output_10EASY.bmp"
    "$OUTPUT_PATH/output_1MEDIUM.bmp"
    "$OUTPUT_PATH/output_2MEDIUM.bmp"
    "$OUTPUT_PATH/output_3MEDIUM.bmp"
    "$OUTPUT_PATH/output_4MEDIUM.bmp"
    "$OUTPUT_PATH/output_5MEDIUM.bmp"
    "$OUTPUT_PATH/output_6MEDIUM.bmp"
    "$OUTPUT_PATH/output_7MEDIUM.bmp"
    "$OUTPUT_PATH/output_8MEDIUM.bmp"
    "$OUTPUT_PATH/output_9MEDIUM.bmp"
    "$OUTPUT_PATH/output_10MEDIUM.bmp"
    "$OUTPUT_PATH/output_1HARD.bmp"
    "$OUTPUT_PATH/output_2HARD.bmp"
    "$OUTPUT_PATH/output_3HARD.bmp"
    "$OUTPUT_PATH/output_4HARD.bmp"
    "$OUTPUT_PATH/output_5HARD.bmp"
    "$OUTPUT_PATH/output_6HARD.bmp"
    "$OUTPUT_PATH/output_7HARD.bmp"
    "$OUTPUT_PATH/output_8HARD.bmp"
    "$OUTPUT_PATH/output_9HARD.bmp"
    "$OUTPUT_PATH/output_10HARD.bmp"
    "$OUTPUT_PATH/output_1IMPOSSIBLE.bmp"
    "$OUTPUT_PATH/output_2IMPOSSIBLE.bmp"
    "$OUTPUT_PATH/output_3IMPOSSIBLE.bmp"
    "$OUTPUT_PATH/output_4IMPOSSIBLE.bmp"
    "$OUTPUT_PATH/output_5IMPOSSIBLE.bmp"
)

# Ensures that output directory exists
if [ ! -d "$OUTPUT_PATH" ]; then
    echo "Creating output directory..."
    mkdir -p "$OUTPUT_PATH"
fi

echo "Processing files..."
for ((i=0; i<${#input_paths[@]}; i++)); do
    echo "Processing: ${input_paths[i]} -> ${output_paths[i]}"
    bin/cell-counter "${input_paths[i]}" "${output_paths[i]}"
done

echo "Done!"
